name: fall_detection_real
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.2
  firebase_app_check: ^0.2.2+4
  intl: ^0.19.0
  fl_chart: ^0.67.0
  flutter_chart: ^0.1.6
  lottie: ^3.1.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.2
  firebase_analytics: ^10.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.jpg
    - assets/images/Login.jpg
    - assets/images/Fall.jpg
    - assets/images/Standing.jpg
